version: "3"

services:

    web:
        image: nginx:latest
        depends_on:
            db:
                condition: service_healthy
        ports:
            - "80:80"
        volumes:
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        networks:
            - tipsandtricks

    db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: '${PGPASSWORD}'
            POSTGRES_USER: '${PGUSER}'
            POSTGRES_DB: '${PGDB}'
            PGDATA: /db/postgres
        ports:
            - "5433:5432"
        command: postgres -c 'max_connections=1000'
        networks:
            - tipsandtricks
        volumes:
            - ./data/postgresql:/var/lib/postgresql/db

networks:
    tipsandtricks:
        driver: bridge

