version: "3"

services:

    reverse-proxy:
        image: nginx:latest
        depends_on:
            db:
              condition: service_healthy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./docker/nginx/webapp.conf:/etc/nginx/sites-available/webapp.conf"
            - "./docker/nginx/init.sh:/usr/local/bin/init.sh"
        command: /bin/sh /usr/local/bin/init.sh

    webapp:
        build: "./docker/webapp/Dockerfile"
        container_name: "webapp_react"
        ports:
            - "3000:3000"
        volumes:
            - "../webapp:/usr/app/webapp"
        command: npm run restart-prod

    db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: '${PGPASSWORD}'
            POSTGRES_USER: '${PGUSER}'
            POSTGRES_DB: '${PGDB}'
            PGDATA: /db/postgres
        ports:
            - "5432:5432"
        command: postgres -c 'max_connections=1000'
        volumes:
            - ./data/postgresql:/var/lib/postgresql/db
        healthcheck:
            test: [ "CMD", "psql", "-U", "matanna", "-d", "tipsandtricks", "-c", "SELECT 1;" ]
            interval: 5s
            timeout: 1m
            retries: 15

