name: Deploy
# Trigger deployment only on push to master branch
on:
    push:
        branches:
            - main

permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout

jobs:
    deploy:
        name: Deploy on server push on main branch
        runs-on: ubuntu-latest

        steps:
            - name: Git clone checkout repository
              uses: actions/checkout@v3

            - name: Deploy
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
                  REMOTE_HOST: ${{ secrets.HOST_DNS }}
                  REMOTE_USER: ${{ secrets.USERNAME }}
                  TARGET: ${{ secrets.TARGET }}

            - name: Containers stop and run
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
                  HOST_DNS: ${{ secrets.HOST_DNS }}
                  USERNAME: ${{ secrets.USERNAME }}
              run: |
                  echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
                  ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOST_DNS} "
                    source /home/${USERNAME}/.profile &&
                    cd /www/tipsandtricks/infra &&
                    docker compose stop &&
                    docker compose --build --no-cache &&
                    docker compose up -d
                  "
